/*
 * ErrorStates.h
 *
 * Created: 1/28/2023 1:14:01 AM
 *  Author: amrmo
 */ 


#ifndef ERRORSTATES_H_
#define ERRORSTATES_H_

typedef enum{
	ES_OK,
	ES_NOK,
	ES_NULL_POINTER,
	ES_PORT_OUT_OF_RANGE,
	ES_PIN_OUT_OF_RANGE,
	ES_CHANNEL_OUT_OF_RANGE,
	ES_COMMON_DETECTION_ERROR,
	ES_EXINT_OUT_OF_RANGE,
	ES_ALLREADY_IS_SET,
	ES_COMPONENT_OUT_OF_RANGE,
	ES_OUT_OF_RANGE,
	ES_ALLREADY_IS_CLEARED,
	ES_CALL_OUT_OF_RANGE,
	ES_TOP_IS_NOT_SELECTED
}ErrorStates_t;

#endif /* ERRORSTATES_H_ */
